### ISSUE TITLE
unexpected keyword argument 'neighbors'

### ISSUE THREAD

**Issue by golnaz-ltri** [VGeorgii/Microsa#1]
Hello, I am trying to replicate the analysis for this package, however when I reach the step for fibers skeletonization and labeling, in the first line of code to define fibre-exe I get a keyword argument error: 
TypeError: label() got an unexpected keyword argument 'neighbors'

All packages are updated as required.

**Comment by VGeorgii** [comment]
> 

Hey!

You are probably using the newest version of skimage library. They have changed a couple of functions. Try next thing: go to the microsaa folder > open fibseg file > find to lines with code _skel_labels = label(skeleton, neighbors = 8)_ and _skel_labels_pruned = label(pruning, neighbors = 8)_ > replace the argument _neighbors = 8_ to _connectivity = 2_. That should help.

**Comment by golnaz-ltri** [comment]
Thank you! This fixed the issue.
